services:
  - type: web
    name: cs121-online-store-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: ""  # Render will automatically add this for PostgreSQL
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com,conrad-tinio.github.io"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://conrad-tinio.github.io"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://conrad-tinio.github.io,https://*.onrender.com" 