# Generated by Django 5.2.1 on 2025-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_tag_products_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productCategory',
        ),
        migrations.AddField(
            model_name='products',
            name='arrival_status',
            field=models.CharField(choices=[('new', 'New Arrivals'), ('recent', 'Recent'), ('classic', 'Classic')], default='classic', max_length=10),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
