# Generated by Django 5.2.1 on 2025-05-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_remove_products_tags_remove_products_productcategory_and_more'),
    ]

    operations = [
    ]
