# Generated by Django 5.2.1 on 2025-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_tag_products_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='arrival_status',
            field=models.CharField(choices=[('new', 'New Arrivals'), ('recent', 'Recent'), ('classic', 'Classic')], db_index=True, default='classic', max_length=10),
        ),
    ]
