# Generated by Django 5.2.1 on 2025-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_remove_products_arrival_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTypeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(help_text='Bootstrap color class (e.g., primary, success, warning, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tag_type'],
            },
        ),
    ]
