# Generated by Django 5.2.1 on 2025-05-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0015_delete_tagtypecolor_tagtype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagtype',
            name='color',
        ),
    ]
