# Generated by Django 5.2.1 on 2025-05-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_remove_tagtype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('dark', 'Black')], default='primary', help_text='Choose the display color for this tag type', max_length=20),
        ),
    ]
